"""empty message

Revision ID: 95b9950682b6
Revises: 
Create Date: 2025-07-11 13:56:16.404175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b9950682b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.Enum('READY_PANEL', 'HANDMADE_PANEL', 'SKETCH_PANEL', name='producttype'), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('delivery_type', sa.Enum('PICKUP', 'YANDEX_DELIVERY', 'OTHER_DELIVERY', name='deliverytype'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ADDED_DESC', 'ADDED_PHOTO', 'ADDED_DELIVERY', 'ACCEPTED', 'CANCELED', name='orderstatus'), server_default='CREATED', nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_product_created', 'orders', ['username', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_product_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
